#pragma once

#include <map>
#include <string>


inline bool ShouldCoalesceMadVRShaderRequest(
	bool selectorsEqual,
	bool applicationPending)
{
	return selectorsEqual && !applicationPending;
}


inline void NormalizeMadVRNlsRuntimeParametersForPreflight(
	std::map<std::string, std::string>& parameters)
{
	// These values are generated by VP as fixed-format finite numbers. They can
	// change for every trusted crop publication without changing HLSL structure.
	// Preserve discrete warp/safe-fit switches because they select preprocessor
	// branches, while canonicalizing continuous geometry for compile caching.
	const std::pair<const char*, const char*> canonical[] = {
		{ "active_height_fraction", "1.00000000" },
		{ "active_left", "0.00000000" },
		{ "active_top", "0.00000000" },
		{ "active_right", "1.00000000" },
		{ "active_bottom", "1.00000000" },
		{ "stretch_ratio", "1.00000000" },
		{ "safe_fit_fraction", "1.00000000" },
	};
	for (const auto& value : canonical)
	{
		auto parameter = parameters.find(value.first);
		if (parameter != parameters.end())
			parameter->second = value.second;
	}
}
